GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/movies

###

PUT http://localhost:5000/api/users/1
Content-type: application/json

{
    "id": 1,
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com",
    "city": "Paris",
    "language": "English",
    "hashPassword": "MONmotDEpass123"
}

###

POST http://localhost:5000/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTY4NzI1ODEyOCwiZXhwIjoxNjg3MjYxNzI4fQ.PPXmVH46uJv3anZV1nwQpZO2celhBb0Sjy8oRJZtcJY
Content-Type: application/json

{
    "title": "Harry Potter",
    "director": "JK Rowling",
    "year": "1999",
    "color": "1",
    "duration": 125
}

###

POST  http://localhost:5000/api/users
Content-type: application/json

{
    "id": "",
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com",
    "city": "Paris",
    "language": "English",
    "hashPassword": "MONmotDEpass456"
}

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "Jackie.chan@example.com",
    "password": "MotDePass,LOL"
}

###

DELETE http://localhost:5000/api/movies/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTY4NzI1ODEyOCwiZXhwIjoxNjg3MjYxNzI4fQ.PPXmVH46uJv3anZV1nwQpZO2celhBb0Sjy8oRJZtcJY
Content-Type: application/json

###